---
title: A hitchhiker's guide to research (个人向科研指南)
author: Jianqiao Wang
date: '2025-02-25'
slug: guide-to-research
categories: []
tags: [随心所欲，不知所言]
subtitle: ''
summary: '学生时期对于学习生活有些思考，趁还记得住（或者说保持着年轻人的思维方式），特别分享出来，希望能对未来学生有所助益。本文随机更新！'
authors: []
lastmod: '2025-02-25T16:57:45+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

学生时期对于学习生活有些思考，趁还记得住（或者说保持着年轻人的思维方式），特别分享出来，希望能对未来学生有所助益。本文随机更新！

### 1. 提问和被提问

提问与被提问是高等教育最重要的部分之一，也是个人成长和科研进步的关键环节，这也是我学到的非常深刻的一课。

#### 面对评论和问题

保持开放和感激的心态。从个人经验来看，每个人的时间和思考力都很宝贵，别人愿意对你的工作提出问题，是因为他们真的感兴趣，认为工作有启发性或者还有很大的提升空间。相反，对于不感兴趣的工作，我们往往只是客套地说一句“很好”或“做得不错”。因此，面对一些尖锐的问题，要实事求是，不要应激反应，不要过度防御，更无需内耗，结合别人的意见，努力提高自己；这种心态可以解决大部分的自我困扰。

另外也要多多思考，你真的听懂别人在问什么？别忘了沟通总是有信息损失的！

#### 学会提出有助益的问题和评论

能够提出准确且深刻的问题是一项高级技能，需要长期不断的训练。因此，从学生时期开始有意识地提高这一能力是非常必要的。但遗憾的是，这种提问能力（或者说批判性思维）我目前也还想到好的方法进行训练，唯一的建议就是多交流、多思考、多阅读、多参加会议。正所谓：“操千曲而后晓声，观千剑而后识器。”

### 2. 博士训练、专业性和一万小时定律

五年的博士训练，严格来说，是一万小时定律的体现，即每年工作 2000 小时 = 8 小时/天 × 250 天，让被训练者从普通人蜕变为小小专家。因此，博士训练是一种职业性训练，就像奥运选手的训练，最终是为了更好的迎接职业挑战，要对其艰苦性有所准备。很多同学选择进一步深造，只是为了延迟成为社会人，这种看法是有问题的。客观来说，读博本身就是一个工作，但好处在于更自由更灵活，你会有更平等和广泛的机会去学习和提高。

另一方面，统计/数据科学社区足够大机会足够多（感谢 senior老师们的努力），你身边的博士同学/coworker从不是你的内卷对手，而是提高你能力的伙伴，是你探索知识边界的同行者。我对很多（学术或非学术）事情的初步认知和理解都来自于小伙伴，自己再不断地修正。因此，请珍惜身边的伙伴，努力从他们的思考中获得启发，不断加强交流，提高自己的能力。另外在学术界，似乎只要有足够独特的思考，就会有好机会（I hope）。

### 3. 关于学术报告和交流

科研最终还是需要交流，院系邀请资深学者举办学术报告、举办各种统计会议都是学术交流活动的重要组成。通常在院系报告中，我们会预留一些时间，让学生与教授交流。然而，许多年轻学子因为性格或一些原因，抓不住这个机会。实际上，这种交流对于认识学术圈、选择未来职业方向，以及培养科研品味都极为重要。为访问学者带去一些好奇心的洗礼，帮助他们保持年轻开放的心态，也是变相让他们满载而归，而不是空手离开。

大多数同学好像不太知道如何（向上）交流，其实大多数老师还是很nice的。这里有一些常见的打开话题的方式，抛砖引玉：

-（1）问一些关于学术社区的情况，想找工作今年竞争激不激烈；问潜在工作机会，是不是有opening

-（2）问一些high-level 关于方向判断的问题：例如用genotype data 真的可以得到准确因果结论吗？我们需要什么条件？

-（3）问一些科研的基本逻辑：例如 seminal work 背后的故事，或是如何想到这个motivation？

-（4）方向相关的，帮助打磨自己research:

 - whether the presentation of the idea/work is clear?
 
 - 某个方向您了解吗？which direction should I explore more? 
 
 - Do you think whether the topic is interesting?

当然交流需要是发自内心的，更需要真诚，坚持真诚交流，就总会有些收获。话说回来，有效的沟通自然是职业性的一种体现，这也是我在博士博后训练中一直被教育的。
